# Generated by Django 4.2 on 2023-05-14 08:38

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='defualt-pic-avater.jpg', null=True, upload_to=store.models.get_file_path_cat),
        ),
    ]
