# Generated by Django 4.2 on 2023-05-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='prouduct',
            new_name='product',
        ),
    ]
