# Generated by Django 4.2 on 2023-05-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='poruduct_qty',
            new_name='porduct_qty',
        ),
    ]
