# Generated by Django 4.2 on 2023-05-20 07:11

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
                ('message', models.TextField(max_length=500)),
                ('width', models.IntegerField()),
                ('heigth', models.IntegerField()),
                ('icon', models.ImageField(blank=True, default='whatsapp-icon.png', height_field=models.IntegerField(), null=True, upload_to=store.models.get_file_path_cat, width_field=models.IntegerField())),
            ],
        ),
    ]
