# Generated by Django 4.2 on 2023-05-20 07:22

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp',
            name='heigth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='icon',
            field=models.ImageField(blank=True, default='whatsapp-icon.png', height_field='heigth', null=True, upload_to=store.models.get_file_path_cat, width_field='width'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='width',
            field=models.CharField(max_length=50),
        ),
    ]
