# Generated by Django 4.2 on 2023-05-20 08:09

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_whatsapp_heigth_alter_whatsapp_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp',
            name='icon',
            field=models.ImageField(blank=True, default='whatsapp-icon.png', height_field=models.CharField(max_length=50), null=True, upload_to=store.models.get_file_path_cat, width_field=models.CharField(max_length=50)),
        ),
    ]
