# Generated by Django 4.2 on 2023-05-20 08:10

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_whatsapp_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp',
            name='icon',
            field=models.ImageField(blank=True, default='whatsapp-icon.png', null=True, upload_to=store.models.get_file_path_cat),
        ),
    ]
